import os, json, smtplib, datetime, urllib.request
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

GMAIL_USER    = os.environ["GMAIL_USER"]
GMAIL_PASS    = os.environ["GMAIL_PASS"]
RECIPIENT     = os.environ.get("RECIPIENT", GMAIL_USER)
ANTHROPIC_KEY = os.environ["ANTHROPIC_API_KEY"]
SEEN_FILE     = "seen_urls.json"
API_BASE      = "https://lanyiapi.com/v1"
MODEL         = "claude-sonnet-4-6"

def get_prompt():
    today = datetime.datetime.utcnow().strftime("%Y-%m-%d")
    return """You are a senior market intelligence analyst for TCL's Global Engineering Business Center, specializing in hospitality TV and commercial display B2B sales across MEA and LATAM markets.

Today is """ + today + """. Generate a comprehensive daily market intelligence briefing covering the following areas. For each item provide actionable insights relevant to a Key Account BD Manager competing against Samsung LYNK and LG ProCentric.

Return ONLY a valid JSON object with this exact structure, no other text before or after:

{
  "sections": [
    {
      "title": "MEA Hotel Market - UAE & Saudi Arabia",
      "items": [
        {
          "headline": "brief headline",
          "insight": "2-3 sentences of actionable market intelligence",
          "relevance": "why this matters for TCL BD strategy",
          "action": "suggested follow-up action"
        }
      ]
    }
  ]
}

Include these 6 sections, each with 3-5 items:

1. MEA Hotel Market - UAE and Saudi Arabia: hotel openings, giga-projects (NEOM, Red Sea, Qiddiya), Vision 2030 hospitality investment, GCC hotel pipeline, key operators (Marriott, Hilton, Accor, IHG) expanding in region

2. LATAM Hotel Market - Brazil and South America: Brazil hotel construction pipeline, Accor/Marriott/IHG expansion in Brazil Colombia Peru Chile, hotelaria trends, hospitality technology adoption

3. Competitive Intelligence - Samsung and LG: Samsung LYNK CAST platform updates, LG ProCentric latest developments, Philips hospitality TV moves, competitor pricing and channel strategy, their weaknesses TCL can exploit

4. Hospitality Technology Trends: IPTV middleware market (Nonius, Acentic, SONIFI, Enseo), Android TV hotel adoption, cloud-based hotel CMS, in-room entertainment trends, system integrator landscape in MEA and LATAM

5. Commercial Display and Digital Signage: hotel lobby display trends, B2B display market MEA and LATAM, digital signage hospitality use cases, AV system integrator opportunities

6. BD Strategy and Opportunities: specific hotel chain RFPs or tenders likely in pipeline, channel partner opportunities, key accounts to target this week in UAE Saudi Arabia Turkey Brazil, talking points against Samsung and LG

Make insights specific, data-driven where possible, and directly actionable for a BD manager making sales calls."""

def call_api(prompt, api_key):
    payload = json.dumps({
        "model": MODEL,
        "max_tokens": 4000,
        "messages": [{"role": "user", "content": prompt}]
    }).encode()

    req = urllib.request.Request(
        API_BASE + "/messages",
        data=payload,
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read().decode())

def extract_sections(response):
    text = ""
    for block in response.get("content", []):
        if block.get("type") == "text":
            text += block.get("text", "")
    start = text.find("{")
    end = text.rfind("}") + 1
    if start == -1 or end == 0:
        print("  [WARN] No JSON found in response")
        print("  Preview: " + text[:300])
        return []
    try:
        data = json.loads(text[start:end])
        return data.get("sections", [])
    except Exception as e:
        print("  [WARN] JSON parse error: " + str(e)[:60])
        return []

def build_markdown(sections, run_date):
    lines = [
        "# TCL Hospitality Market Intelligence - Daily Briefing",
        "Date: " + run_date,
        "Markets: UAE, Saudi Arabia, Turkey, Brazil, Colombia, Peru, Panama, Chile",
        "Competing against: Samsung LYNK | LG ProCentric",
        "",
        "---",
        "",
    ]
    for s in sections:
        lines.append("## " + s.get("title", ""))
        for item in s.get("items", []):
            lines.append("### " + item.get("headline", ""))
            lines.append(item.get("insight", ""))
            lines.append("")
            if item.get("relevance"):
                lines.append("Relevance: " + item["relevance"])
            if item.get("action"):
                lines.append("Action: " + item["action"])
            lines.append("")
        lines.append("")
    lines.append("---")
    lines.append("Generated by TCL Market Monitor - " + run_date)
    return "\n".join(lines)

def build_html_email(sections, run_date):
    total_items = sum(len(s.get("items", [])) for s in sections)

    html = (
        "<!DOCTYPE html><html><head><meta charset='utf-8'></head>"
        "<body style='margin:0;padding:20px;background:#eef1f5;font-family:Arial,sans-serif;'>"
        "<div style='max-width:760px;margin:auto;'>"
        "<div style='background:#0d1b2a;padding:28px 32px;border-radius:10px 10px 0 0;'>"
        "<h1 style='color:#fff;margin:0 0 4px;font-size:20px;'>TCL Market Intelligence</h1>"
        "<p style='color:#7eb8f7;margin:0;font-size:13px;'>Hospitality TV and Commercial Display - Daily Briefing</p>"
        "<div style='margin-top:16px;'>"
        "<span style='background:rgba(255,255,255,0.1);color:#cde;padding:5px 12px;border-radius:20px;font-size:12px;margin-right:8px;'>Date: " + run_date[:10] + "</span>"
        "<span style='background:rgba(255,255,255,0.1);color:#cde;padding:5px 12px;border-radius:20px;font-size:12px;margin-right:8px;'>" + str(total_items) + " insights</span>"
        "<span style='background:rgba(255,255,255,0.1);color:#cde;padding:5px 12px;border-radius:20px;font-size:12px;'>" + str(len(sections)) + " sections</span>"
        "</div></div>"
        "<div style='background:#fff;padding:8px 32px 32px;border:1px solid #dde;border-top:none;border-radius:0 0 10px 10px;'>"
    )

    for s in sections:
        html += (
            "<div style='padding-top:28px;'>"
            "<h2 style='font-size:15px;font-weight:700;color:#0d1b2a;border-bottom:2px solid #e63946;padding-bottom:8px;margin:0 0 16px;'>" + s.get("title", "") + "</h2>"
        )
        for item in s.get("items", []):
            html += (
                "<div style='margin-bottom:14px;padding:16px;background:#f8f9fa;border-radius:8px;border-left:4px solid #e63946;'>"
                "<p style='font-size:14px;font-weight:700;color:#0d1b2a;margin:0 0 8px;'>" + item.get("headline", "") + "</p>"
                "<p style='font-size:13px;color:#444;margin:0 0 8px;line-height:1.6;'>" + item.get("insight", "") + "</p>"
            )
            if item.get("relevance"):
                html += "<p style='font-size:12px;color:#666;margin:4px 0;'><strong>Why it matters:</strong> " + item["relevance"] + "</p>"
            if item.get("action"):
                html += "<p style='font-size:12px;color:#e63946;margin:4px 0 0;'><strong>Action:</strong> " + item["action"] + "</p>"
            html += "</div>"
        html += "</div>"

    html += (
        "<div style='margin-top:36px;padding-top:20px;border-top:1px solid #eee;text-align:center;'>"
        "<p style='font-size:11px;color:#aaa;line-height:1.8;margin:0;'>"
        "TCL Global Engineering Business Center<br>"
        "Hospitality TV and Commercial Display - Key Account BD<br>"
        "MEA: UAE, Saudi Arabia, Turkey | LATAM: Brazil, Colombia, Peru, Panama, Chile<br><br>"
        "Attach the .md file to NotebookLM for your daily audio briefing"
        "</p></div></div></body></html>"
    )
    return html

def send_email(html_body, markdown_content, run_date):
    msg = MIMEMultipart("mixed")
    msg["Subject"] = "TCL Market Intel - " + run_date[:10]
    msg["From"]    = GMAIL_USER
    msg["To"]      = RECIPIENT
    msg.attach(MIMEText(html_body, "html"))
    attachment = MIMEText(markdown_content, "plain", "utf-8")
    attachment.add_header("Content-Disposition", "attachment",
                          filename="tcl_intel_" + run_date[:10] + ".md")
    msg.attach(attachment)
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_USER, GMAIL_PASS)
        server.sendmail(GMAIL_USER, RECIPIENT, msg.as_string())
    print("  Email sent to " + RECIPIENT)

def save_markdown(content, run_date):
    os.makedirs("output", exist_ok=True)
    path = "output/tcl_intel_" + run_date[:10] + ".md"
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print("  Markdown saved: " + path)

def main():
    run_date = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    print("TCL Market Monitor - " + run_date)
    print("API: " + API_BASE + " | Model: " + MODEL)

    print("Calling API...")
    try:
        response = call_api(get_prompt(), ANTHROPIC_KEY)
        sections = extract_sections(response)
        print("Sections returned: " + str(len(sections)))
    except Exception as e:
        print("ERROR: " + str(e))
        sections = []

    total = sum(len(s.get("items", [])) for s in sections)
    print("Total insights: " + str(total))

    md   = build_markdown(sections, run_date)
    html = build_html_email(sections, run_date)
    save_markdown(md, run_date)
    send_email(html, md, run_date)
    print("Done.")

if __name__ == "__main__":
    main()
