import os, json, smtplib, datetime, time, random
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from duckduckgo_search import DDGS
from duckduckgo_search.exceptions import RatelimitException

GMAIL_USER   = os.environ[“GMAIL_USER”]
GMAIL_PASS   = os.environ[“GMAIL_PASS”]
RECIPIENT    = os.environ.get(“RECIPIENT”, GMAIL_USER)
MAX_RESULTS  = 8
MAX_AGE_DAYS = 2
SEEN_FILE    = “seen_urls.json”

QUERIES = [
“hotel hospitality Marriott Hilton Accor opening 2026”,
“Dubai UAE Saudi Arabia hotel construction hospitality”,
“Brazil hotel IPTV hospitality hotelaria Brasil”,
“LATAM Colombia Peru Chile hotel hospitality Wyndham IHG”,
“Samsung LYNK LG ProCentric hotel TV hospitality display”,
“hotel in-room entertainment IPTV middleware digital signage”,
“Turkey hotel hospitality Marriott otel konaklama 2026”,
“NEOM Red Sea Vision 2030 hotel resort hospitality”,
]

MUST_HAVE = [
“hotel”, “hospitality”, “resort”, “hotelaria”, “hoteleiro”,
“otel”, “iptv”, “in-room”, “display”, “signage”,
“marriott”, “hilton”, “accor”, “wyndham”, “ihg”, “radisson”,
“hyatt”, “novotel”, “ibis”, “sheraton”, “intercontinental”,
“samsung lynk”, “lg procentric”, “philips hospitality”,
“nonius”, “acentic”, “sonifi”, “enseo”,
“hotel tv”, “hotel technology”, “hotel construction”,
“hotel opening”, “hotel development”, “hotel investment”,
“digital signage”, “commercial display”, “guestroom”,
“hitec”, “set-top”, “middleware”,
]

MUST_NOT = [
“world cup”, “fifa”, “nfl”, “nba”, “celebrity”, “time 100”,
“concert”, “music festival”, “oscar”, “grammy”,
“cryptocurrency”, “bitcoin”, “stock market”,
“crime”, “murder”, “accident”, “weather forecast”,
“election”, “senator”, “congress”, “taylor swift”,
“morgan wallen”, “college football”, “box office”,
]

def is_relevant(title, body):
text = (title + “ “ + (body or “”)).lower()
if any(bad in text for bad in MUST_NOT):
if not any(kw in text for kw in [“hotel”, “hospitality”, “hotelaria”, “resort”]):
return False
return any(kw in text for kw in MUST_HAVE)

def load_seen_urls():
if os.path.exists(SEEN_FILE):
with open(SEEN_FILE, “r”) as f:
data = json.load(f)
cutoff = datetime.datetime.now() - datetime.timedelta(days=14)
return {url: ts for url, ts in data.items()
if datetime.datetime.fromisoformat(ts) > cutoff}
return {}

def save_seen_urls(seen):
with open(SEEN_FILE, “w”) as f:
json.dump(seen, f, indent=2)

def fetch_news(queries, max_results, max_age_days, seen_urls):
articles = []
seen_urls_run = set()
cutoff = datetime.datetime.now() - datetime.timedelta(days=max_age_days)

```
with DDGS() as ddgs:
    for query in queries:
        time.sleep(6 + random.uniform(0, 3))
        for attempt in range(3):
            try:
                raw = list(ddgs.news(query, max_results=max_results, timelimit="w"))
                break
            except RatelimitException:
                wait = 20 + attempt * 15
                print("  [RATELIMIT] waiting " + str(wait) + "s")
                time.sleep(wait)
                raw = []
            except Exception as e:
                print("  [WARN] " + str(e)[:60])
                raw = []
                break

        kept = 0
        for a in raw:
            url = a.get("url", "")
            if not url or url in seen_urls or url in seen_urls_run:
                continue
            title = a.get("title", "")
            body  = a.get("body", "")
            if not is_relevant(title, body):
                continue
            seen_urls_run.add(url)
            pub = a.get("date", "")
            try:
                pd = datetime.datetime.fromisoformat(pub.replace("Z", "+00:00")).replace(tzinfo=None)
                if pd < cutoff:
                    continue
            except Exception:
                pass
            articles.append({
                "title":  title,
                "source": a.get("source", "Unknown"),
                "date":   pub[:10] if pub else "N/A",
                "url":    url,
                "body":   body,
            })
            kept += 1

        print("  Query [" + query[:45] + "]: " + str(kept) + " kept")

return articles, {a["url"]: datetime.datetime.now().isoformat() for a in articles}
```

def build_markdown(articles, run_date):
lines = [
“# TCL Hospitality Market Intelligence - Daily Briefing”,
“Date: “ + run_date,
“Total new articles: “ + str(len(articles)),
“Markets: UAE, Saudi Arabia, Turkey, Brazil, Colombia, Peru, Panama, Chile”,
“”,
“—”,
“”,
]
for a in articles:
lines.append(”### “ + a[“title”])
lines.append(“Source: “ + a[“source”] + “ | Date: “ + a[“date”])
lines.append(a[“url”] + “\n”)
if a[“body”]:
lines.append(a[“body”][:600] + “\n”)
lines.append(”—”)
lines.append(“Generated by TCL Market Monitor - “ + run_date)
return “\n”.join(lines)

def build_html_email(articles, run_date):
total = len(articles)
html = (
“<!DOCTYPE html><html><head><meta charset='utf-8'></head>”
“<body style='margin:0;padding:20px;background:#eef1f5;font-family:Arial,sans-serif;'>”
“<div style='max-width:720px;margin:auto;'>”
“<div style='background:#0d1b2a;padding:28px 32px;border-radius:10px 10px 0 0;'>”
“<h1 style='color:#fff;margin:0 0 4px;font-size:20px;'>TCL Market Intelligence</h1>”
“<p style='color:#7eb8f7;margin:0;font-size:13px;'>Hospitality TV and Commercial Display - Daily Briefing</p>”
“<div style='margin-top:16px;'>”
“<span style='background:rgba(255,255,255,0.1);color:#cde;padding:5px 12px;border-radius:20px;font-size:12px;margin-right:8px;'>Date: “ + run_date[:10] + “</span>”
“<span style='background:rgba(255,255,255,0.1);color:#cde;padding:5px 12px;border-radius:20px;font-size:12px;'>” + str(total) + “ new articles</span>”
“</div></div>”
“<div style='background:#fff;padding:8px 32px 32px;border:1px solid #dde;border-top:none;border-radius:0 0 10px 10px;'>”
“<div style='padding-top:28px;'>”
“<h2 style='font-size:15px;font-weight:700;color:#0d1b2a;border-bottom:2px solid #e63946;padding-bottom:8px;margin:0 0 16px;'>Hospitality and AV Market News</h2>”
)

```
if not articles:
    html += "<p style='color:#ccc;font-style:italic;font-size:13px;'>No new relevant articles found today.</p>"
else:
    for a in articles:
        body = (a["body"][:280] + "...") if len(a["body"]) > 280 else a["body"]
        html += (
            "<div style='margin-bottom:12px;padding:16px;background:#f8f9fa;"
            "border-radius:8px;border-left:4px solid #e63946;'>"
            "<a href='" + a["url"] + "' style='font-size:14px;font-weight:600;"
            "color:#0d1b2a;text-decoration:none;display:block;'>" + a["title"] + "</a>"
            "<div style='margin-top:6px;'>"
            "<span style='font-size:11px;color:#e63946;font-weight:700;text-transform:uppercase;'>" + a["source"] + "</span>"
            "<span style='font-size:11px;color:#999;margin-left:8px;'>" + a["date"] + "</span>"
            "</div>"
            + ("<p style='font-size:13px;color:#555;margin:8px 0 0;line-height:1.55;'>" + body + "</p>" if body else "") +
            "</div>"
        )

html += (
    "</div>"
    "<div style='margin-top:36px;padding-top:20px;border-top:1px solid #eee;text-align:center;'>"
    "<p style='font-size:11px;color:#aaa;line-height:1.8;margin:0;'>"
    "TCL Global Engineering Business Center<br>"
    "Hospitality TV and Commercial Display - Key Account BD<br>"
    "MEA: UAE, Saudi Arabia, Turkey | LATAM: Brazil, Colombia, Peru, Panama, Chile<br><br>"
    "Attach the .md file to NotebookLM for your daily audio briefing"
    "</p></div></div></body></html>"
)
return html
```

def send_email(html_body, markdown_content, run_date):
msg = MIMEMultipart(“mixed”)
msg[“Subject”] = “TCL Market Intel - “ + run_date[:10]
msg[“From”]    = GMAIL_USER
msg[“To”]      = RECIPIENT
msg.attach(MIMEText(html_body, “html”))
attachment = MIMEText(markdown_content, “plain”, “utf-8”)
attachment.add_header(“Content-Disposition”, “attachment”,
filename=“tcl_intel_” + run_date[:10] + “.md”)
msg.attach(attachment)
with smtplib.SMTP_SSL(“smtp.gmail.com”, 465) as server:
server.login(GMAIL_USER, GMAIL_PASS)
server.sendmail(GMAIL_USER, RECIPIENT, msg.as_string())
print(”  Email sent to “ + RECIPIENT)

def save_markdown(content, run_date):
os.makedirs(“output”, exist_ok=True)
path = “output/tcl_intel_” + run_date[:10] + “.md”
with open(path, “w”, encoding=“utf-8”) as f:
f.write(content)
print(”  Markdown saved: “ + path)

def main():
run_date = datetime.datetime.utcnow().strftime(”%Y-%m-%d %H:%M UTC”)
print(“TCL Market Monitor - “ + run_date)
seen_urls = load_seen_urls()
print(“Dedup cache: “ + str(len(seen_urls)) + “ URLs”)
articles, new_seen = fetch_news(QUERIES, MAX_RESULTS, MAX_AGE_DAYS, seen_urls)
print(“Total relevant articles: “ + str(len(articles)))
seen_urls.update(new_seen)
save_seen_urls(seen_urls)
md   = build_markdown(articles, run_date)
html = build_html_email(articles, run_date)
save_markdown(md, run_date)
send_email(html, md, run_date)
print(“Done. “ + str(len(new_seen)) + “ new URLs cached.”)

if **name** == “**main**”:
main()
